service: demo2

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: post
          cors: true
          integration: lambda
          authorizer:
            name: authorizer
            arn: arn:aws:cognito-idp:us-east-1:704855577349:userpool/us-east-1_EwX5GFtD9
            claims:
              - email
              - username

  postSignUp:
    handler: handler.postSignup
    events:
      - cognitoUserPool:
          pool: ${self:service}-user-pool
          trigger: PostConfirmation
